apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-service
  template:
    metadata:
      labels:
        app: quote-service
    spec:
      containers:
        - name: quote-service
          image: shashwat2712/quoteservice:16819470589
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: quote-service
spec:
  selector:
    app: quote-service
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
