name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [ ApiGateway, FrontendApplication, QuoteService ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        
      - name: Set Image Tag
        id: vars
        run: |
          SERVICE=${{ matrix.service }}
          SERVICE_TAG=$(echo "$SERVICE" | tr '[:upper:]' '[:lower:]')
          IMAGE_TAG="${SERVICE_TAG}-${{ github.run_id }}"
          echo "SERVICE_TAG=$SERVICE_TAG" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          echo "🔧 Building $SERVICE_TAG from ${{ matrix.service }}/app.dockerfile"
          docker build -f ${{ matrix.service }}/app.dockerfile -t $DOCKER_USER/$REPO_NAME:$IMAGE_TAG ${{ matrix.service }}
          
          echo "📤 Pushing image to DockerHub..."
          docker push $DOCKER_USER/$REPO_NAME:$IMAGE_TAG

      - name: ✅ Done
        run: echo "✔️ Successfully pushed $DOCKER_USER/$REPO_NAME:$IMAGE_TAG"
